
package org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Converter", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://currencyconverter.kowabunga.net/converter.asmx?WSDL")
public class Converter
    extends Service
{

    private final static URL CONVERTER_WSDL_LOCATION;
    private final static WebServiceException CONVERTER_EXCEPTION;
    private final static QName CONVERTER_QNAME = new QName("http://tempuri.org/", "Converter");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://currencyconverter.kowabunga.net/converter.asmx?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONVERTER_WSDL_LOCATION = url;
        CONVERTER_EXCEPTION = e;
    }

    public Converter() {
        super(__getWsdlLocation(), CONVERTER_QNAME);
    }

    public Converter(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONVERTER_QNAME, features);
    }

    public Converter(URL wsdlLocation) {
        super(wsdlLocation, CONVERTER_QNAME);
    }

    public Converter(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONVERTER_QNAME, features);
    }

    public Converter(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Converter(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ConverterSoap
     */
    @WebEndpoint(name = "ConverterSoap")
    public ConverterSoap getConverterSoap() {
        return super.getPort(new QName("http://tempuri.org/", "ConverterSoap"), ConverterSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConverterSoap
     */
    @WebEndpoint(name = "ConverterSoap")
    public ConverterSoap getConverterSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "ConverterSoap"), ConverterSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONVERTER_EXCEPTION!= null) {
            throw CONVERTER_EXCEPTION;
        }
        return CONVERTER_WSDL_LOCATION;
    }

}
