
package org.tempuri;

import java.math.BigDecimal;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ConverterSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    org.tempuri.ObjectFactory.class,
    org.w3._2001.xmlschema.ObjectFactory.class
})
public interface ConverterSoap {


    /**
     * 
     * @return
     *     returns org.tempuri.ArrayOfString
     */
    @WebMethod(operationName = "GetCurrencies", action = "http://tempuri.org/GetCurrencies")
    @WebResult(name = "GetCurrenciesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetCurrencies", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCurrencies")
    @ResponseWrapper(localName = "GetCurrenciesResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCurrenciesResponse")
    public ArrayOfString getCurrencies();

    /**
     * 
     * @param currency
     * @param rateDate
     * @return
     *     returns java.math.BigDecimal
     */
    @WebMethod(operationName = "GetCurrencyRate", action = "http://tempuri.org/GetCurrencyRate")
    @WebResult(name = "GetCurrencyRateResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetCurrencyRate", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCurrencyRate")
    @ResponseWrapper(localName = "GetCurrencyRateResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCurrencyRateResponse")
    public BigDecimal getCurrencyRate(
        @WebParam(name = "Currency", targetNamespace = "http://tempuri.org/")
        String currency,
        @WebParam(name = "RateDate", targetNamespace = "http://tempuri.org/")
        XMLGregorianCalendar rateDate);

    /**
     * 
     * @param rateDate
     * @return
     *     returns org.tempuri.GetCurrencyRatesResponse.GetCurrencyRatesResult
     */
    @WebMethod(operationName = "GetCurrencyRates", action = "http://tempuri.org/GetCurrencyRates")
    @WebResult(name = "GetCurrencyRatesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetCurrencyRates", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCurrencyRates")
    @ResponseWrapper(localName = "GetCurrencyRatesResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCurrencyRatesResponse")
    public org.tempuri.GetCurrencyRatesResponse.GetCurrencyRatesResult getCurrencyRates(
        @WebParam(name = "RateDate", targetNamespace = "http://tempuri.org/")
        XMLGregorianCalendar rateDate);

    /**
     * 
     * @param rateDate
     * @param currencyTo
     * @param currencyFrom
     * @return
     *     returns java.math.BigDecimal
     */
    @WebMethod(operationName = "GetConversionRate", action = "http://tempuri.org/GetConversionRate")
    @WebResult(name = "GetConversionRateResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetConversionRate", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetConversionRate")
    @ResponseWrapper(localName = "GetConversionRateResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetConversionRateResponse")
    public BigDecimal getConversionRate(
        @WebParam(name = "CurrencyFrom", targetNamespace = "http://tempuri.org/")
        String currencyFrom,
        @WebParam(name = "CurrencyTo", targetNamespace = "http://tempuri.org/")
        String currencyTo,
        @WebParam(name = "RateDate", targetNamespace = "http://tempuri.org/")
        XMLGregorianCalendar rateDate);

    /**
     * 
     * @param amount
     * @param rateDate
     * @param currencyTo
     * @param currencyFrom
     * @return
     *     returns java.math.BigDecimal
     */
    @WebMethod(operationName = "GetConversionAmount", action = "http://tempuri.org/GetConversionAmount")
    @WebResult(name = "GetConversionAmountResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetConversionAmount", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetConversionAmount")
    @ResponseWrapper(localName = "GetConversionAmountResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetConversionAmountResponse")
    public BigDecimal getConversionAmount(
        @WebParam(name = "CurrencyFrom", targetNamespace = "http://tempuri.org/")
        String currencyFrom,
        @WebParam(name = "CurrencyTo", targetNamespace = "http://tempuri.org/")
        String currencyTo,
        @WebParam(name = "RateDate", targetNamespace = "http://tempuri.org/")
        String rateDate,
        @WebParam(name = "Amount", targetNamespace = "http://tempuri.org/")
        BigDecimal amount);

    /**
     * 
     * @param currency
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetCultureInfo", action = "http://tempuri.org/GetCultureInfo")
    @WebResult(name = "GetCultureInfoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetCultureInfo", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCultureInfo")
    @ResponseWrapper(localName = "GetCultureInfoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCultureInfoResponse")
    public String getCultureInfo(
        @WebParam(name = "Currency", targetNamespace = "http://tempuri.org/")
        String currency);

    /**
     * 
     * @param toCurrency
     * @param fromCurrency
     * @param ds
     * @param tableIndex
     * @param columnName
     * @return
     *     returns org.tempuri.ConvertDataTableColumnResponse.Ds
     */
    @WebMethod(operationName = "ConvertDataTableColumn", action = "http://tempuri.org/ConvertDataTableColumn")
    @WebResult(name = "ds", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ConvertDataTableColumn", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConvertDataTableColumn")
    @ResponseWrapper(localName = "ConvertDataTableColumnResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConvertDataTableColumnResponse")
    public org.tempuri.ConvertDataTableColumnResponse.Ds convertDataTableColumn(
        @WebParam(name = "ds", targetNamespace = "http://tempuri.org/")
        org.tempuri.ConvertDataTableColumn.Ds ds,
        @WebParam(name = "TableIndex", targetNamespace = "http://tempuri.org/")
        int tableIndex,
        @WebParam(name = "ColumnName", targetNamespace = "http://tempuri.org/")
        String columnName,
        @WebParam(name = "FromCurrency", targetNamespace = "http://tempuri.org/")
        String fromCurrency,
        @WebParam(name = "ToCurrency", targetNamespace = "http://tempuri.org/")
        String toCurrency);

    /**
     * 
     * @return
     *     returns javax.xml.datatype.XMLGregorianCalendar
     */
    @WebMethod(operationName = "GetLastUpdateDate", action = "http://tempuri.org/GetLastUpdateDate")
    @WebResult(name = "GetLastUpdateDateResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetLastUpdateDate", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetLastUpdateDate")
    @ResponseWrapper(localName = "GetLastUpdateDateResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetLastUpdateDateResponse")
    public XMLGregorianCalendar getLastUpdateDate();

}
